### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by hobarrera** [vaab/colour#39]
Building 0.1.4 from source fails:

```
Missing version information: running './autogen.sh'...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/setup.py", line 17, in <module>
    from setuptools import setup
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/d2to1/util.py", line 204, in cfg_to_args
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/d2to1/util.py", line 439, in wrap_commands
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 589, in get_command_list
    cmdclass = ep.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    d2to1=True
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 325, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 446, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 855, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1127, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1139, in obtain
    return installer(requirement)
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 518, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/setup.py", line 17, in <module>
    from setuptools import setup
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/d2to1/util.py", line 204, in cfg_to_args
  File "/tmp/easy_install-gi3u_ihf/d2to1-0.2.12.post1/d2to1/util.py", line 439, in wrap_commands
  File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 589, in get_command_list
    cmdclass = ep.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'tasks'
```

**Comment by blueyed** [comment]
This is caused by an invalid entrypoint (no related to this package).
For me (on Arch Linux) it is python-cli_helpers: 
```
cat /usr/lib/python3.6/site-packages/cli_helpers-0.2.3-py3.6.egg-info/entry_points.txt                                                                                                 🐍?
[distutils.commands]
docs = tasks:docs
lint = tasks:lint
test = tasks:test
```

**Comment by blueyed** [comment]
Fixed in cli_helpers: https://github.com/dbcli/cli_helpers/pull/29.

Should get closed here I think.

**Comment by dreua** [comment]
@WhyNotHugo I think this issue is resolved, could you close it?
